test "item comparisons":

	# Basic Material Comparisons

	set {_a} to a dirt
	set {_b} to a diamond block

	assert {_a} is a dirt with "{_a} is not a dirt (it should be)"
	assert {_a} is not a diamond block with "{_a} is a diamond block (it shouldn't be)"

	assert {_b} is not a dirt with "{_b} is a dirt (it shouldn't be)"
	assert {_b} is a diamond block with "{_b} is not a diamond block (it should be)"

	assert {_a} is not {_b} with "{_a} is {_b} (it shouldn't be) (Basic Material Comparisons)"
	assert {_b} is not {_a} with "{_b} is {_a} (it shouldn't be) (Basic Material Comparisons)"

	# Different Name Comparisons

	set {_a} to a diamond
	set {_b} to a diamond named "Fake Diamond"

	assert {_a} is a diamond with "{_a} is not a diamond (it should be)"
	assert {_a} is a diamond named "" with "{_a} is not an unnamed diamond (it should be)"
	assert {_a} is not a diamond named "Fake Diamond" with "{_a} is a diamond named ""Fake Diamond"" (it shouldn't be)"

	assert {_b} is a diamond with "{_b} is not a diamond (it should be)"
	assert {_b} is not a diamond named "" with "{_b} is an unnamed diamond (it shouldn't be)"
	assert {_b} is a diamond named "Fake Diamond" with "{_b} is not a diamond named ""Fake Diamond"" (it should be)"

	assert {_a} is not {_b} with "{_a} is {_b} (it shouldn't be) (Different Name Comparisons)"
	assert {_b} is {_a} with "{_b} is not {_a} (it should be) (Different Name Comparisons)"

	# Different Enchantment Comparisons

	set {_a} to a dirt of sharpness 1
	set {_b} to a dirt of sharpness 2

	assert {_a} is a dirt with "{_a} is not a dirt (it should be)"
	assert {_a} is a dirt of sharpness 1 with "{_a} is not a dirt of sharpness 1 (it should be)"
	assert {_a} is not a dirt of sharpness 2 with "{_a} is a dirt of sharpness 2 (it shouldn't be)"
	assert a dirt of sharpness 1 is {_a} with "a dirt of sharpness 1 is not {_a} (it should be)"

	assert {_b} is a dirt with "{_b} is not a dirt (it should be)"
	assert {_b} is not a dirt of sharpness 1 with "{_b} is a dirt of sharpness 1 (it shouldn't be)"
	assert {_b} is a dirt of sharpness 2 with "{_b} is not a dirt of sharpness 2 (it should be)"
	assert a dirt of sharpness 1 is not {_b} with "a dirt of sharpness 1 is {_b} (it shouldn't be)"

	assert {_a} is not {_b} with "{_a} is {_b} (it shouldn't be) (Different Enchantment Comparisons"
	assert {_b} is not {_a} with "{_b} is {_a} (it shouldn't be) (Different Enchantment Comparisons)"

	# Same Material and Same Lore BUT Different Enchantment

	set {_a} to a diamond of sharpness 1 with lore "Lore 1" and "Lore 2"
	set {_b} to a diamond of sharpness 2 with lore "Lore 1" and "Lore 2"

	assert {_a} is a diamond of sharpness 1 with lore "Lore 1" and "Lore 2" with "{_a} is not a diamond of sharpness 1 with lore ""Lore 1"" and ""Lore 2"" (it should be)"
	assert {_a} is not a diamond of sharpness 2 with lore "Lore 1" and "Lore 2" with "{_a} is a diamond of sharpness 2 with lore ""Lore 1"" and ""Lore 2"" (it shouldn't be)"

	assert {_b} is a diamond of sharpness 2 with lore "Lore 1" and "Lore 2" with "{_b} is not a diamond of sharpness 2 with lore ""Lore 1"" and ""Lore 2"" (it should be)"
	assert {_b} is not a diamond of sharpness 1 with lore "Lore 1" and "Lore 2" with "{_b} is a diamond of sharpness 1 with lore ""Lore 1"" and ""Lore 2"" (it shouldn't be)"

	assert {_a} is not {_b} with "{_a} is {_b} (it shouldn't be) (Same Material and Same Lore BUT Different Enchantment)"
	assert {_b} is not {_a} with "{_b} is {_a} (it shouldn't be) (Same Material and Same Lore BUT Different Enchantment)"

	# Skull Comparisons

	set {_a} to a skeleton skull named "Skulliest Skull"
	set {_b} to an dragon head named "Skully Skull"

	assert {_a} is a skeleton skull with "{_a} is not a skeleton skull (it should be)"
	assert {_a} is not a skeleton skull named "" with "{_a} is an unnamed skeleton skull (it shouldn't be)"
	assert {_a} is a skeleton skull named "Skulliest Skull" with "{_a} is not a skeleton skull named ""Skulliest Skull"" (it should be)"

	assert {_a} is not an dragon head with "{_a} is an dragon head (it should't be)"
	assert {_a} is not an dragon head named "Skulliest Skull" with "{_a} is an dragon head named ""Skulliest Skull"" (it shouldn't be)"

	assert {_b} is an dragon head with "{_b} is not an dragon head (it should be)"
	assert {_b} is not an dragon head named "" with "{_b} is an unnamed dragon head (it shouldn't be)"
	assert {_b} is an dragon head named "Skully Skull" with "{_b} is not an dragon head named ""Skully Skull"" (it should be)"

	assert {_b} is not a skeleton skull with "{_b} is a skeleton skull (it shouldn't be)"
	assert {_b} is not a skeleton skull named "Skully Skull" with "{_b} is a skeleton skull named ""Skully Skull"" (it shouldn't be)"

	assert {_a} is not {_b} with "{_a} is {_b} (it shouldn't be) (Skull Comparisons)"
	assert {_b} is not {_a} with "{_b} is {_a} (it shouldn't be) (Skull Comparisons)"

	# player head Comparisons

	set {_p1} to "APickledWalrus" parsed as an offlineplayer
	set {_p2} to "ShaneBee" parsed as an offlineplayer
	set {_a} to skull of {_p1}
	set {_b} to skull of {_p2}

	assert {_a} is a player head with "{_a} is not a player head (it should be)"
	assert {_a} is the skull of {_p1} with "{_a} is not the skull of {_p1} (it should be)"
	assert {_a} is not the skull of {_p2} with "{_a} is the skull of {_p2} (it shouldn't be)"

	assert {_b} is a player head with "{_b} is not a player head (it should be)"
	assert {_b} is the skull of {_p2} with "{_b} is not the skull of {_p2} (it should be)"
	assert {_b} is not the skull of {_p1} with "{_b} is the skull of {_p1} (it shouldn't be)"

	assert {_a} is not {_b} with "{_a} is {_b} (it shouldn't be) (player head Comparisons)"
	assert {_b} is not {_a} with "{_b} is {_a} (it shouldn't be) (player head Comparisons)"

	# Remove / Remove All Tests

	set block at spawn of world "world" to air
	set block at spawn of world "world" to a chest

	set {_inventory} to inventory of block at spawn of world "world"
	add 64 diamond and 64 diamond named "Fake Diamond" to {_inventory}

	remove 4 diamond named "" from {_inventory}
	assert {_inventory} contains 60 diamond and 64 diamond named "Fake Diamond" with "4 unnamed diamond were not properly removed."

	remove 4 diamond named "Fake Diamond" from {_inventory}
	assert {_inventory} contains 60 diamond and 60 diamond named "Fake Diamond" with "4 named diamond were not properly removed."

	set {_size} to number of diamond in {_inventory}
	assert {_size} = 120 with "{_inventory} should have 120 diamond in it, but it doesn't. Number of diamond: '%{_size}%'"

	assert {_inventory} is not empty with "{_inventory} is empty, but it shouldn't be."
	remove all diamond from {_inventory}
	assert {_inventory} is empty with "{_inventory} still has diamond, but it shouldn't."

	set block at spawn of world "world" to air
