test "spawn fish types":
	spawn a cod at spawn of world "world":
		set {_e} to entity
	assert entitytype of {_e} is cod with "failed to spawn a cod"
	delete entity within {_e}

	spawn a salmon at spawn of world "world":
		set {_e} to entity
	assert entitytype of {_e} is salmon with "failed to spawn a salmon"
	delete entity within {_e}

	spawn a pufferfish at spawn of world "world":
		set {_e} to entity
	assert entitytype of {_e} is pufferfish with "failed to spawn a puffer fish"
	delete entity within {_e}

	spawn a tropical fish at spawn of world "world":
		set {_e} to entity
	assert entitytype of {_e} is tropical fish with "failed to spawn a tropical fish"
	delete entity within {_e}

	parse if running minecraft "1.19":
		spawn a tadpole at spawn of world "world":
			set {_e} to entity
		assert entitytype of {_e} is tadpole with "failed to spawn a tadpole"
		delete entity within {_e}
