test "block condition":
	# Materials that are not Blocks
	assert emerald isn't a block with "emerald shouldn't be a block"
	assert stick isn't a block with "stick shouldn't be a block"

	# Materials that are Blocks
	assert diamond ore is a block with "diamond ore should be a block"
	assert air is a block with "air should be a block"
	assert cave air is a block with "cave air should be a block"
	assert oak stairs is a block with "oak stairs should be a block"
