test "max stack":
	assert max stack size of diamond sword is 1 with "diamond sword max stack size failed"
	assert max stack size of bucket is 16 with "bucket max stack size failed"
	assert max stack size of dirt is 64 with "dirt max stack size failed"

	set {_i} to 1 of oak log
	assert max stack size of {_i} = 64 with "Oak log should have a max stack size of 64"
	set max stack size of {_i} to 3
	assert max stack size of {_i} = 3 with "Custom oak log should have a max stack size of 3"
	set max stack size of {_i} to 100
	assert max stack size of {_i} = 99 with "Max stack size is limited to 99"
	set max stack size of {_i} to -3
	assert max stack size of {_i} = 1 with "Max stack size must be >= 1"
	reset max stack size of {_i}
	assert max stack size of {_i} = 64 with "Oak log should reset max stack size to 64"
