test "lowest/highest solid block (old height)" when running below minecraft "1.18":

	# highest solid block
	set {_oldBlock::1} to block data of block at location(0, 255, 0, "world")
	set {_oldBlock::2} to block data of block at location(0, 254, 0, "world")
	set {_oldBlock::3} to block data of block at location(0, 253, 0, "world")
	set block at location(0, 255, 0, "world") to air
	set block at location(0, 254, 0, "world") to air
	set block at location(0, 253, 0, "world") to dirt
	set {_highest} to highest solid block at location(0, 64, 0, "world")
	assert type of {_highest} is dirt with "highest block is not dirt (got '%type of {_highest}%')"
	assert location of {_highest} is location(0, 253, 0, "world") with "highest block is not at 0,253,0 (got '%location of {_highest}%')"
	set block at location(0, 255, 0, "world") to {_oldBlock::1}
	set block at location(0, 254, 0, "world") to {_oldBlock::2}
	set block at location(0, 253, 0, "world") to {_oldBlock::3}

	# lowest solid block
	set {_oldBlock::1} to block data of block at location(0, 0, 0, "world")
	set {_oldBlock::2} to block data of block at location(0, 1, 0, "world")
	set {_oldBlock::3} to block data of block at location(0, 2, 0, "world")
	set block at location(0, 0, 0, "world") to air
	set block at location(0, 1, 0, "world") to air
	set block at location(0, 2, 0, "world") to dirt
	set {_lowest} to lowest solid block at location(0, 64, 0, "world")
	assert type of {_lowest} is dirt with "lowest block is not dirt (got '%type of {_lowest}%')"
	assert location of {_lowest} is location(0, 2, 0, "world") with "lowest block is not at 0,2,0 (got '%location of {_lowest}%')"
	set block at location(0, 0, 0, "world") to {_oldBlock::1}
	set block at location(0, 1, 0, "world") to {_oldBlock::2}
	set block at location(0, 2, 0, "world") to {_oldBlock::3}

test "lowest/highest solid block (new height)" when running minecraft "1.18":

	# highest solid block
	set {_oldBlock::1} to block data of block at location(0, 319, 0, "world")
	set {_oldBlock::2} to block data of block at location(0, 318, 0, "world")
	set {_oldBlock::3} to block data of block at location(0, 317, 0, "world")
	set block at location(0, 319, 0, "world") to air
	set block at location(0, 318, 0, "world") to air
	set block at location(0, 317, 0, "world") to dirt
	set {_highest} to highest solid block at location(0, 64, 0, "world")
	assert type of {_highest} is dirt with "highest block is not dirt (got '%type of {_highest}%')"
	assert location of {_highest} is location(0, 317, 0, "world") with "highest block is not at 0,317,0 (got '%location of {_highest}%')"
	set block at location(0, 319, 0, "world") to {_oldBlock::1}
	set block at location(0, 318, 0, "world") to {_oldBlock::1}
	set block at location(0, 317, 0, "world") to {_oldBlock::1}

	# lowest solid block
	set {_oldBlock::1} to block data of block at location(0, -64, 0, "world")
	set {_oldBlock::2} to block data of block at location(0, -63, 0, "world")
	set {_oldBlock::3} to block data of block at location(0, -62, 0, "world")
	set block at location(0, -64, 0, "world") to air
	set block at location(0, -63, 0, "world") to air
	set block at location(0, -62, 0, "world") to dirt
	set {_lowest} to lowest solid block at location(0, 64, 0, "world")
	assert type of {_lowest} is dirt with "lowest block is not dirt (got '%type of {_lowest}%')"
	assert location of {_lowest} is location(0, -62, 0, "world") with "lowest block is not at 0,-62,0 (got '%location of {_lowest}%')"
	set block at location(0, -64, 0, "world") to {_oldBlock::1}
	set block at location(0, -63, 0, "world") to {_oldBlock::2}
	set block at location(0, -62, 0, "world") to {_oldBlock::3}

