test "item inventory":
  set {_shulker} to itemstack of green shulker box
  assert inventory of {_shulker} is set with "Failed to get shulker inventory"
  set slot 1 of inventory of {_shulker} to itemstack of dirt
  assert slot 1 of inventory of {_shulker} is itemstack of dirt with "Failed to set slot in shulker inventory"

  set {_chest} to itemstack of chest
  assert inventory of {_chest} is set with "Failed to get chest inventory"
  set slot 1 of inventory of {_chest} to itemstack of dirt
  assert slot 1 of inventory of {_chest} is itemstack of dirt with "Failed to set slot in chest inventory"

  assert inventory of itemstack of dirt is not set with "Inventory was found for an item without an inventory"
