test "item with fire resistance" when running minecraft "1.20.5":

	# single item
	set {_item} to itemstack of diamond with fire resistance
	assert {_item} is fire resistant with "{_item} was not fire resistant"

	# multiple items
	set {_item} to fire resistant itemstack of diamond
	set {_item2} to itemstack of paper
	enchant {_item2} with fire protection 1
	assert ({_item} and {_item2}) are fire resistant with "{_item} and {_item2} are unexpectedly not fire resistant"

	if running minecraft "1.21":
		set {_item} to itemstack of netherite sword
		assert {_item} is fire resistant with "Netherite should be fire resistant by default"
