test "amount of items":
	set {_inventory} to a hopper inventory named "test"
	assert the amount of stone in {_inventory} is 0 with "default amount failed"
	add stone to {_inventory}
	assert the amount of stone in {_inventory} is 1 with "single amount failed"
	add itemstack of stone named "bread" to {_inventory}
	assert the amount of stone in {_inventory} is 2 with "different named items amount failed"
	add itemstack of 25 of iron ingot to {_inventory}
	assert the amount of stone in {_inventory} is 2 with "add different item amount failed"
	assert the amount of iron ingot in {_inventory} is 25 with "add 25 item amount failed"
	remove stone from {_inventory}
	assert the amount of stone in {_inventory} is 0 with "removed all amount failed"
