test "freeze time" when running minecraft "1.18":
	spawn cow at spawn of world "world":
		assert freeze time of event-entity is set with "freeze time get failed"
		set freeze time of event-entity to 3 seconds
		assert freeze time of event-entity is 3 seconds with "freeze time set failed"
		add 2 seconds to freeze time of event-entity
		assert freeze time of event-entity is 5 seconds with "freeze time add failed"
		add 10 seconds to freeze time of event-entity
		assert freeze time of event-entity is 15 seconds with "freeze time add failed" # freeze time should not be capped at event-entity's max freeze time (7 seconds for a cow)
	
		remove 6 seconds from freeze time of event-entity
		assert freeze time of event-entity is 9 seconds with "freeze time remove failed"
		remove 10 seconds from freeze time of event-entity
		assert freeze time of event-entity is 0 seconds with "freeze time remove failed" # freeze time should not be negative
		delete freeze time of event-entity
		assert freeze time of event-entity is 0 seconds with "freeze time delete failed"

		delete event-entity
