test "attributes 1" when running minecraft "1.21.3":
	spawn cow at spawn of world "world":
		assert movement speed attribute of event-entity is set with "attribute get failed"
		set movement speed attribute of event-entity to 3.14
		assert movement speed attribute of event-entity is 3.14 with "attribute set failed"
		add 5 to movement speed attribute of event-entity
		assert movement speed attribute of event-entity is 8.14 with "attribute add failed"
		remove 4 from movement speed attribute of event-entity
		assert movement speed attribute of event-entity is 4.14 with "attribute remove failed"
		remove 10 from movement speed attribute of event-entity
		assert movement speed attribute of event-entity is -5.86 with "attribute remove failed" # Negative attribute values should be safe
		delete movement speed attribute of event-entity
		assert movement speed attribute of event-entity is 0 with "attribute delete failed"
		delete event-entity

test "attributes 2" when running below minecraft "1.21.3":
	spawn cow at spawn of world "world":
		assert generic.movement speed attribute of event-entity is set with "attribute get failed"
		set generic.movement speed attribute of event-entity to 3.14
		assert generic.movement speed attribute of event-entity is 3.14 with "attribute set failed"
		add 5 to generic.movement speed attribute of event-entity
		assert generic.movement speed attribute of event-entity is 8.14 with "attribute add failed"
		remove 4 from generic.movement speed attribute of event-entity
		assert generic.movement speed attribute of event-entity is 4.14 with "attribute remove failed"
		remove 10 from generic.movement speed attribute of event-entity
		assert generic.movement speed attribute of event-entity is -5.86 with "attribute remove failed" # Negative attribute values should be safe
		delete generic.movement speed attribute of event-entity
		assert generic.movement speed attribute of event-entity is 0 with "attribute delete failed"
		delete event-entity
