test "SimpleJUnitTest" when running JUnit:
	# Setup our objective for this script test to complete with the JUnit test.
	ensure junit test "org.skriptlang.skript.test.tests.regression.SimpleJUnitTest" completes "piggy died"

on damage of pig:
	# Check that this is indeed our correct test to match with the JUnit test we want.
	junit test is "org.skriptlang.skript.test.tests.regression.SimpleJUnitTest"

	# Using the JUnit name is not required, just another example.
	assert custom name of victim is "Simple JUnit Test" with "piggy was not the same"

	assert damage is 100 with "damage was not 100"

	# Tell our objective that our runtime objective has been completed which was an entity damage event.
	complete objective "piggy died" for junit test "org.skriptlang.skript.test.tests.regression.SimpleJUnitTest"
