test "explode with fire effect/condition":
	spawn a tnt at spawn of world "world"
	assert last spawned tnt doesn't cause an incendiary explosion with "a primed tnt's explosion shouldn't cause fire by default"
	make the last spawned tnt's explosion fiery
	assert last spawned tnt causes an incendiary explosion with "a primed tnt's explosion should cause fire when set to"
	make the last spawned tnt's explosion not fiery
	assert last spawned tnt doesn't cause an incendiary explosion with "a primed tnt's explosion shouldn't cause fire when set not to"
	delete last spawned tnt
